-- v1.8-0001 minimal schema skeleton
CREATE TABLE IF NOT EXISTS events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  level VARCHAR(16) NOT NULL,
  source VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  message TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS traders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  trader_name VARCHAR(64) UNIQUE NOT NULL,
  strategy VARCHAR(64) NOT NULL,
  risk_mode VARCHAR(16) NOT NULL,
  run_mode VARCHAR(16) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS market_regimes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(32) NOT NULL,
  score INT NOT NULL,
  metrics_json JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
